# Copy this file to config.yaml and fill in your values

# Discord settings
bot_token: "YOUR_DISCORD_BOT_TOKEN_HERE"
client_id: "YOUR_DISCORD_CLIENT_ID_HERE"
status_message: "Powered by Gemini"

# Gemini settings
gemini_api_key: "YOUR_GOOGLE_AI_API_KEY_HERE"
default_model: "gemini-2.5-flash"  # Options: gemini-2.5-flash, gemini-2.5-pro
default_system_prompt: |
  You are a helpful AI assistant in a Discord server.
  Be friendly, concise, and engaging.
  Today's date is {date}. The current time is {time}.

enable_search_grounding: true  # Enable Google Search integration

# Message limits
max_text: 100000  # Maximum characters per message
max_images: 5  # Maximum images per message
max_messages: 25  # Maximum messages in conversation history
max_urls: 3  # Maximum image URLs to extract from text

# Personalization limits
max_user_description_length: 500  # Maximum characters for user descriptions

# Discord behavior
use_plain_responses: false  # Set to true to use plain text instead of embeds
allow_dms: true  # Allow direct messages to the bot

# Permissions
# Note: Empty lists mean "allow all" for allowed_ids
permissions:
  users:
    admin_ids: []  # Add your Discord user ID here: [123456789012345678]
    allowed_ids: []  # Leave empty to allow everyone, or add specific user IDs
    blocked_ids: []  # Add user IDs to block
  roles:
    allowed_ids: []  # Leave empty to allow all roles, or add specific role IDs
    blocked_ids: []  # Add role IDs to block
  channels:
    allowed_ids: []  # Leave empty to allow all channels, or add specific channel/category IDs
    blocked_ids: []  # Add channel/category IDs to block